<a href="https://colab.research.google.com/github/polaya813/polaya813/blob/main/Copia_de_ENTREGABLE_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DESARROLLO DE LOS PUNTOS DEL ENTREGABLE 5

Importar librerias

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import io
from scipy import stats # Opcional, pandas .skew() y .kurt() son suficientes
# Configuraciones opcionales para mejor visualización
plt.style.use('seaborn-v0_8-whitegrid') # Estilo de gráficos
pd.set_option('display.max_columns', None) # Mostrar todas las columnas

pd.set_option('display.float_format', lambda x: '%.2f' % x) # Formato de flotantes

print("Librerías importadas.")

Librerías importadas.

# Exploración inicial del dataset

In [ ]:
# Carga del dataset desde una URL
dataset_url = "https://raw.githubusercontent.com/reginatwopointo/Life-Expectancy-Exploratory-Data-Analysis-and-Visualization/main/Life%20Expectancy%20Data.csv"
df_life = pd.read_csv(dataset_url)

## Exploracion inicial del dataset

In [ ]:
# Mostrar primeras n lineas del dataset
df_life.head(20)

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.00,263,62,0.01,71.27962362,65.00,1154,19.10,83,6.00,8.16,65.00,0.10,584.26,33736494.00,17.20,17.30,0.48,10.10
1,Afghanistan,2014,Developing,59.90,271,64,0.01,73.52358168,62.00,492,18.60,86,58.00,8.18,62.00,0.10,612.70,32758200.00,17.50,17.50,0.48,10.00
2,Afghanistan,2013,Developing,59.90,268,66,0.01,73.21924272,64.00,430,18.10,89,62.00,8.13,64.00,0.10,631.74,31731688.00,17.70,17.70,0.47,9.90
3,Afghanistan,2012,Developing,59.50,272,69,0.01,78.1842153,67.00,2787,17.60,93,67.00,8.52,67.00,0.10,669.96,31000000.00,17.90,18.00,0.46,9.80
4,Afghanistan,2011,Developing,59.20,275,71,0.01,7.097108703,68.00,3013,17.20,97,68.00,7.87,68.00,0.10,63.54,29785990.00,18.20,18.20,0.45,9.50
5,Afghanistan,2010,Developing,58.80,279,74,0.01,79.67936736,66.00,1989,16.70,102,66.00,9.20,66.00,0.10,553.33,28831670.00,18.40,18.40,0.45,9.20
6,Afghanistan,2009,Developing,58.60,281,77,0.01,56.76221682,63.00,2861,16.20,106,63.00,9.42,63.00,0.10,445.89,28433100.00,18.60,18.70,0.43,8.90
7,Afghanistan,2008,Developing,58.10,287,80,0.03,25.87392536,64.00,1599,15.70,110,64.00,8.33,64.00,0.10,373.36,27294310.00,18.80,18.90,0.43,8.70
8,Afghanistan,2007,Developing,57.50,295,82,0.02,10.91015598,63.00,1141,15.20,113,63.00,6.73,63.00,0.10,369.84,26616792.00,19.00,19.10,0.41,8.40
9,Afghanistan,2006,Developing,57.30,295,84,0.03,17.17151751,64.00,1990,14.70,116,58.00,7.43,58.00,0.10,272.56,25893450.00,19.20,19.30,0.41,8.10
10,Afghanistan,2005,Developing,57.30,291,85,0.02,1.388647732,66.00,1296,14.20,118,58.00,8.70,58.00,0.10,25.29,25779800.00,19.30,19.50,0.40,7.90
11,Afghanistan,2004,Developing,57.00,293,87,0.02,15.29606643,67.00,466,13.80,120,5.00,8.79,5.00,0.10,219.14,24118979.00,19.50,19.70,0.38,6.80
12,Afghanistan,2003,Developing,56.70,295,87,0.01,11.08905273,65.00,798,13.40,122,41.00,8.82,41.00,0.10,198.73,23648510.00,19.70,19.90,0.37,6.50
13,Afghanistan,2002,Developing,56.20,3,88,0.01,16.88735091,64.00,2486,13.00,122,36.00,7.76,36.00,0.10,187.85,21979923.00,19.90,2.20,0.34,6.20
14,Afghanistan,2001,Developing,55.30,316,88,0.01,10.5747282,63.00,8762,12.60,122,35.00,7.80,33.00,0.10,117.50,21610000.00,2.10,2.40,0.34,5.90
15,Afghanistan,2000,Developing,54.80,321,88,0.01,10.42496,62.00,6532,12.20,122,24.00,8.20,24.00,0.10,114.56,20780000.00,2.30,2.50,0.34,5.50
16,Albania,2015,Developing,77.80,74,0,4.60,364.9752287,99.00,0,58.00,1,99.00,6.00,99.00,0.10,3954.23,2887300.00,1.20,1.30,0.76,14.20
17,Albania,2014,Developing,77.50,8,0,4.51,428.7490668,98.00,0,57.20,1,98.00,5.88,98.00,0.10,4575.76,2889140.00,1.20,1.30,0.76,14.20
18,Albania,2013,Developing,77.20,84,0,4.76,430.8769785,99.00,0,56.50,1,99.00,5.66,99.00,0.10,4414.72,2895920.00,1.30,1.40,0.76,14.20
19,Albania,2012,Developing,76.90,86,0,5.14,412.4433563,99.00,9,55.80,1,99.00,5.59,99.00,0.10,4247.61,2903000.00,1.30,1.40,0.75,14.20

In [ ]:
# Mostrar ultimas n lineas del dataset
df_life.tail(8)

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
2872,Zimbabwe,2007,Developing,46.60,67,29,3.88,29.81456607,72.00,242,28.20,46,73.00,4.47,73.00,23.70,397.00,13329990.00,8.20,8.20,0.41,9.60
2873,Zimbabwe,2006,Developing,45.40,7,28,4.57,34.26216876,68.00,212,27.90,45,71.00,5.12,7.00,26.80,414.80,13124267.00,8.60,8.60,0.41,9.50
2874,Zimbabwe,2005,Developing,44.60,717,28,4.14,8.7174087,65.00,420,27.50,43,69.00,6.44,68.00,30.30,444.77,12943200.00,9.00,9.00,0.41,9.30
2875,Zimbabwe,2004,Developing,44.30,723,27,4.36,0,68.00,31,27.10,42,67.00,7.13,65.00,33.60,454.37,12777511.00,9.40,9.40,0.41,9.20
2876,Zimbabwe,2003,Developing,44.50,715,26,4.06,0,7.00,998,26.70,41,7.00,6.52,68.00,36.70,453.35,12633897.00,9.80,9.90,0.42,9.50
2877,Zimbabwe,2002,Developing,44.80,73,25,4.43,0,73.00,304,26.30,40,73.00,6.53,71.00,39.80,57.35,12552500.00,1.20,1.30,0.43,10.00
2878,Zimbabwe,2001,Developing,45.30,686,25,1.72,0,76.00,529,25.90,39,76.00,6.16,75.00,42.10,548.59,12366165.00,1.60,1.70,0.43,9.80
2879,Zimbabwe,2000,Developing,46.00,665,24,1.68,0,79.00,1483,25.50,39,78.00,7.10,78.00,43.50,547.36,12222251.00,11.00,11.20,0.43,9.80

In [ ]:
# Información general del Dataframe
df_life.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2880 entries, 0 to 2879
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          2880 non-null   object
 1   Year                             2880 non-null   int64
 2   Status                           2880 non-null   object
 3   Life expectancy                  2880 non-null   float64
 4   Adult Mortality                  2880 non-null   int64
 5   infant deaths                    2880 non-null   int64
 6   Alcohol                          2842 non-null   float64
 7   percentage expenditure           2880 non-null   object
 8   Hepatitis B                      2539 non-null   float64
 9   Measles                          2880 non-null   int64
 10   BMI                             2864 non-null   float64
 11  under-five deaths                2880 non-null   int64
 12  Polio                            2872 non-null   float64
 13  Total expenditure                2824 non-null   float64
 14  Diphtheria                       2872 non-null   float64
 15   HIV/AIDS                        2880 non-null   float64
 16  GDP                              2507 non-null   float64
 17  Population                       2447 non-null   float64
 18   thinness  1-19 years            2864 non-null   float64
 19   thinness 5-9 years              2864 non-null   float64
 20  Income composition of resources  2736 non-null   float64
 21  Schooling                        2736 non-null   float64
dtypes: float64(14), int64(5), object(3)
memory usage: 495.1+ KB

In [ ]:
# Obtener las estadísticas descriptivas
df_life.describe(include='all')

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
count,2880,2880.00,2880,2880.00,2880.00,2880.00,2842.00,2880,2539.00,2880.00,2864.00,2880.00,2872.00,2824.00,2872.00,2880.00,2507.00,2447.00,2864.00,2864.00,2736.00,2736.00
unique,180,NaN,2,NaN,NaN,NaN,NaN,2321,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Afghanistan,NaN,Developing,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,16,NaN,2368,NaN,NaN,NaN,NaN,472,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,2007.50,NaN,69.37,164.58,30.48,4.79,NaN,80.67,2428.70,38.30,42.19,82.86,5.94,82.85,1.75,7498.40,36118057.18,4.85,4.88,0.63,12.06
std,NaN,4.61,NaN,9.45,123.37,119.06,4.03,NaN,24.13,11565.49,19.95,161.98,23.06,2.50,23.03,5.12,14222.57,145830520.72,4.44,4.53,0.21,3.26
min,NaN,2000.00,NaN,36.30,1.00,0.00,0.01,NaN,1.00,0.00,1.00,0.00,3.00,0.37,2.00,0.10,1.68,13692.00,0.10,0.10,0.00,0.00
25%,NaN,2003.75,NaN,63.48,75.00,0.00,1.16,NaN,76.00,0.00,19.30,0.00,78.00,4.26,79.00,0.10,464.02,1770710.00,1.60,1.50,0.50,10.10
50%,NaN,2007.50,NaN,72.10,144.00,3.00,3.99,NaN,91.00,17.00,43.50,4.00,93.00,5.72,93.00,0.10,1814.49,6576877.00,3.30,3.40,0.68,12.40
75%,NaN,2011.25,NaN,75.80,226.00,21.00,7.97,NaN,96.00,352.25,56.12,26.00,97.00,7.50,97.00,0.70,6282.31,19853445.50,7.20,7.20,0.78,14.30
max,NaN,2015.00,NaN,89.00,723.00,1800.00,17.87,NaN,99.00,212183.00,77.60,2500.00,99.00,17.60,99.00,50.60,119172.74,1395398000.00,27.70,28.60,0.95,20.70

In [ ]:
# Dimensiones del dataframe
# (filas, columnas)
df_life.shape

(2880, 22)

# Limpieza y Preparación de datos

### Renombrar Columnas

In [ ]:
# Columnas sin estandarizar
df_life.columns

Index(['Country', 'Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling'],
      dtype='object')

In [ ]:
# Renombrar Columnas

df_life.columns = df_life.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('-', '_')

In [ ]:
df_life.columns

Index(['country', 'year', 'status', 'life_expectancy', 'adult_mortality',
       'infant_deaths', 'alcohol', 'percentage_expenditure', 'hepatitis_b',
       'measles', 'bmi', 'under_five_deaths', 'polio', 'total_expenditure',
       'diphtheria', 'hiv/aids', 'gdp', 'population', 'thinness__1_19_years',
       'thinness_5_9_years', 'income_composition_of_resources', 'schooling'],
      dtype='object')

In [ ]:
# Ver primera n columnas

df_life.columns[:5]

Index(['country', 'year', 'status', 'life_expectancy', 'adult_mortality'], dtype='object')

### Manejo de valores faltantes

In [ ]:
# Porcemtaje de nulos por columnas
print((df_life.isnull().sum() / len(df_life)) * 100)

country                            0.00
year                               0.00
status                             0.00
life_expectancy                    0.00
adult_mortality                    0.00
infant_deaths                      0.00
alcohol                            1.32
percentage_expenditure             0.00
hepatitis_b                       11.84
measles                            0.00
bmi                                0.56
under_five_deaths                  0.00
polio                              0.28
total_expenditure                  1.94
diphtheria                         0.28
hiv/aids                           0.00
gdp                               12.95
population                        15.03
thinness__1_19_years               0.56
thinness_5_9_years                 0.56
income_composition_of_resources    5.00
schooling                          5.00
dtype: float64

### Verificación de Tipos de Datos

# Análisis Estadístico Descriptivo Univariado

## Medidas estadísticas

1. Medidas de Tendencia Central: Calcula la media, mediana y moda.
2. Medidas de Dispersión: Calcula el rango, varianza y desviación estándar.
3. Medidas de Forma: Calcula la asimetría (skewness) y curtosis.

In [ ]:
# Tabla de Frecuencia - variable status

## Visualización Univariada

In [ ]:
# Histograma y KDE: Para la variable life_expectancy.

In [ ]:
# Boxplot: Para la variable life_expectancy, y también separada por status.

In [ ]:
# Gráfico de Barras: Para la frecuencia de la variable status.