<a href="https://colab.research.google.com/github/polaya813/polaya813/blob/main/Lab_26_reto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Paso 1: Cargar librerías y datos

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
!pip install unidecode
import unidecode

Requirement already satisfied: unidecode in /usr/local/lib/python3.12/dist-packages (1.4.0)

In [6]:
# Cargar el dataset
url = "https://raw.githubusercontent.com/datasets/population/main/data/population.csv"
df_raw = pd.read_csv(url)
df = df_raw.copy()
df.head()

  Country Name Country Code  Year  Value
0        Aruba          ABW  1960  54922
1        Aruba          ABW  1961  55578
2        Aruba          ABW  1962  56320
3        Aruba          ABW  1963  57002
4        Aruba          ABW  1964  57619

Paso 2: Exploración inicial

In [7]:
print("Dimensiones:", df.shape)
df.info()
df.describe(include='all')

Dimensiones: (17195, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17195 entries, 0 to 17194
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country Name  17195 non-null  object
 1   Country Code  17195 non-null  object
 2   Year          17195 non-null  int64
 3   Value         17195 non-null  int64
dtypes: int64(2), object(2)
memory usage: 537.5+ KB

       Country Name Country Code          Year         Value
count         17195        17195  17195.000000  1.719500e+04
unique          265          265           NaN           NaN
top        Zimbabwe          ZWE           NaN           NaN
freq             65           65           NaN           NaN
mean            NaN          NaN   1992.030532  2.182379e+08
std             NaN          NaN     18.760828  7.142151e+08
min             NaN          NaN   1960.000000  2.715000e+03
25%             NaN          NaN   1976.000000  1.019463e+06
50%             NaN          NaN   1992.000000  6.790788e+06
75%             NaN          NaN   2008.000000  4.706578e+07
max             NaN          NaN   2024.000000  8.141809e+09

Paso 3: Identificar y eliminar duplicados
python

In [8]:
print("Duplicados:", df.duplicated().sum())
df = df.drop_duplicates()

Duplicados: 0

Paso 4: Manejo de valores nulos

In [ ]:
df.isnull().sum()
# Imputar valores numéricos con la media
df['Age'] = df['Age'].fillna(df['Age'].mean())
# Rellenar texto con “Sin datos”
df['Job Title'] = df['Job Title'].fillna("Sin datos")